# Generated by Django 4.2.7 on 2024-11-20 11:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_active_trades', models.IntegerField(default=10, help_text='Maximum number of active trades')),
                ('trade_amount', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Amount in USDT per trade', max_digits=10)),
                ('min_liquidity_usd', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Minimum liquidity in USD', max_digits=10)),
                ('max_price_drop_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Maximum price drop from peak (%)', max_digits=5)),
                ('profit_target_multiplier', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Profit target multiplier (e.g., 3 = 300%)', max_digits=5)),
                ('listing_check_interval', models.IntegerField(default=5, help_text='New listings check interval (seconds)')),
                ('price_check_interval', models.IntegerField(default=10, help_text='Price monitoring interval (seconds)')),
                ('slippage_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Slippage tolerance (%)', max_digits=5)),
                ('gas_limit', models.IntegerField(default=300000, help_text='Gas limit for transactions')),
                ('trading_enabled', models.BooleanField(default=True, help_text='Enable/disable automatic trading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Configuration',
                'verbose_name_plural': 'Trading Configuration',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=42, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ANALYZING', 'Analyzing'), ('BUYING', 'Buying'), ('BOUGHT', 'Bought'), ('SELLING', 'Selling'), ('SOLD', 'Sold'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='NEW', max_length=20)),
                ('price_first_seen', models.DecimalField(decimal_places=18, max_digits=30)),
                ('price_peak', models.DecimalField(decimal_places=18, max_digits=30)),
                ('current_price', models.DecimalField(decimal_places=18, max_digits=30)),
                ('pool_address', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=30)),
                ('entry_price', models.DecimalField(decimal_places=18, max_digits=30)),
                ('exit_price', models.DecimalField(decimal_places=18, max_digits=30, null=True)),
                ('status', models.CharField(choices=[('BOUGHT', 'Bought'), ('SOLD', 'Sold')], max_length=10)),
                ('buy_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('sell_amount', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('buy_order_id', models.CharField(max_length=66)),
                ('sell_order_id', models.CharField(max_length=66, null=True)),
                ('buy_timestamp', models.DateTimeField()),
                ('sell_timestamp', models.DateTimeField(null=True)),
                ('sell_reason', models.CharField(choices=[('DROP_FROM_PEAK', 'Dropped from peak (20%)'), ('BELOW_ENTRY', 'Below entry price'), ('PROFIT_TARGET', '3x profit target'), ('MANUAL', 'Manual sell')], max_length=20, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.currency')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
    ]
