# Generated by Django 4.2.7 on 2024-11-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bscconfig',
            name='token_analyze_url_id',
            field=models.CharField(default='56', max_length=20),
        ),
        migrations.AddField(
            model_name='currency',
            name='analyze_data',
            field=models.JSONField(null=True),
        ),
    ]
