# Generated by Django 4.2.7 on 2024-11-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_bscconfig_factory_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='current_price',
            field=models.DecimalField(decimal_places=18, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='pool_address',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price_first_seen',
            field=models.DecimalField(decimal_places=18, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price_peak',
            field=models.DecimalField(decimal_places=18, max_digits=30, null=True),
        ),
    ]
