# Generated by Django 4.2.7 on 2024-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_currency_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bscconfig',
            name='main_api_url',
            field=models.CharField(default='', max_length=128),
        ),
    ]
